[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.070339+00:00] request.INFO: Matched route "contao_managerapi_server_adminuser__invoke". {"route":"contao_managerapi_server_adminuser__invoke","route_parameters":{"_route":"contao_managerapi_server_adminuser__invoke","_controller":"_ContaoManager\\Contao\\ManagerApi\\Controller\\Server\\AdminUserController"},"request_uri":"https://update.handyservice4you.at/contao-manager.phar.php/api/server/admin-user","method":"GET"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.109194+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"api","authenticators":5} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.109202+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.109257+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\LoginAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.109259+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\WebauthnAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.109307+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\WebauthnAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.109309+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.109356+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\PasswordlessAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.109358+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.110084+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.110097+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"api","authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\TokenAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.112719+00:00] security.INFO: Authenticator successful! {"token":{"_ContaoManager\\Symfony\\Component\\Security\\Http\\Authenticator\\Token\\PostAuthenticationToken":"PostAuthenticationToken(user=\"cmadmin-hs4y-0504\", roles=\"ROLE_ADMIN\")"},"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:51.113083+00:00] security.DEBUG: Authenticator set no success response: request continues. {"authenticator":"_ContaoManager\\Contao\\ManagerApi\\Security\\JwtAuthenticator"} []
[05-Apr-2025 08:08:52 UTC] [2025-04-05T08:08:52.027657+00:00] app.CRITICAL: Uncaught PHP Exception _ContaoManager\Symfony\Component\Process\Exception\ProcessFailedException: "The command "'/opt/plesk/php/8.2/bin/php' '-q' '-dmax_execution_time=0' '-dmemory_limit=-1' '-ddisplay_errors=0' '-ddisplay_startup_errors=0' '-derror_reporting=0' '-dallow_url_fopen=1' '-ddisable_functions=' '-ddate.timezone=UTC' '/var/www/vhosts/handyservice4you.at/update.handyservice4you.at/vendor/contao/manager-bundle/bin/contao-console' 'contao:user:list' '--format=json' '--column=username' '--column=name' '--column=admin' '--column=dateAdded' '--column=lastLogin' '--no-interaction'" failed.  Exit Code: 255(Unknown error)  Working directory: /var/www/vhosts/handyservice4you.at/update.handyservice4you.at  Output: ================   Error Output: ================ 08:08:52 CRITICAL  [console] Error thrown while running command "contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction","message" => "An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'"]  In ExceptionConverter.php line 118:                                                                                   An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied f     or user 'root'@'localhost'                                                                                                                                     In Exception.php line 24:                                                                        SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'                                                                         In Driver.php line 33:                                                                        SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'                                                                         contao:user:list [--column COLUMN] [--admins] [--format FORMAT]  " at phar:///var/www/vhosts/handyservice4you.at/update.handyservice4you.at/public/contao-manager.phar.php/api/Process/ContaoConsole.php line 146 {"exception":"[object] (_ContaoManager\\Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"'/opt/plesk/php/8.2/bin/php' '-q' '-dmax_execution_time=0' '-dmemory_limit=-1' '-ddisplay_errors=0' '-ddisplay_startup_errors=0' '-derror_reporting=0' '-dallow_url_fopen=1' '-ddisable_functions=' '-ddate.timezone=UTC' '/var/www/vhosts/handyservice4you.at/update.handyservice4you.at/vendor/contao/manager-bundle/bin/contao-console' 'contao:user:list' '--format=json' '--column=username' '--column=name' '--column=admin' '--column=dateAdded' '--column=lastLogin' '--no-interaction'\" failed.\n\nExit Code: 255(Unknown error)\n\nWorking directory: /var/www/vhosts/handyservice4you.at/update.handyservice4you.at\n\nOutput:\n================\n\n\nError Output:\n================\n08:08:52 CRITICAL  [console] Error thrown while running command \"contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction\". Message: \"An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'\" [\"exception\" => Doctrine\\DBAL\\Exception\\DriverException { …},\"command\" => \"contao:user:list --format=json --column=username --column=name --column=admin --column=dateAdded --column=lastLogin --no-interaction\",\"message\" => \"An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'\"]\n\nIn ExceptionConverter.php line 118:\n                                                                               \n  An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied f  \n  or user 'root'@'localhost'                                                   \n                                                                               \n\nIn Exception.php line 24:\n                                                                    \n  SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'  \n                                                                    \n\nIn Driver.php line 33:\n                                                                    \n  SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'  \n                                                                    \n\ncontao:user:list [--column COLUMN] [--admins] [--format FORMAT]\n\n at phar:///var/www/vhosts/handyservice4you.at/update.handyservice4you.at/public/contao-manager.phar.php/api/Process/ContaoConsole.php:146)"} []
